# This is the network config written by 'subiquity'
network:
  ethernets:
    ens33:
      dhcp4: no
      addresses:
        - 192.168.2.50/24
      gateway4: 192.168.2.1
      nameservers:
        addresses: [8.8.8.8, 8.8.4.4] 
    ens38:
      dhcp4: no
      addresses:
        - 10.0.0.250/24
      gateway4: 192.168.2.1
  version: 2
